openapi: 3.0.2
servers:
  - url: http://localhost:8080/
info:
  description: This is a OpenApi specification for MyHome backend service.
  version: 2.0.0
  title: Swagger MyHome - OpenAPI 3.0
tags:
  - name: Users
  - name: Houses
paths:
  /users:
    post:
      tags:
        - Users
      description: "Create a new user"
      operationId: signUp
      requestBody:
        description: CreateUserRequest aggregate fields
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: "if user created"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '409':
          description: "if user already exists"
    get:
      tags:
        - Users
      description: "Lists all users"
      operationId: listAllUsers
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: "Returns list of users"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserDetailsResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetUserDetailsResponse'
  /users/{userId}:
    get:
      tags:
        - Users
      description: "Get details of a user given userId"
      operationId: getUserDetails
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
          description: ID of the user to get
      responses:
        '200':
          description: "If userId is valid. Response body has the details"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserDetailsResponseUser'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetUserDetailsResponseUser'
        '404':
          description: "If userId is invalid"
  /houses:
    get:
      tags:
        - Houses
      summary: Get list of houses
      description: ''
      operationId: listAllHouses
      parameters:
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHouseDetailsResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetHouseDetailsResponse'
  '/houses/{houseId}':
    get:
      tags:
        - Houses
      summary: Get house by id
      description: ''
      operationId: getHouseDetails
      parameters:
        - in: path
          name: houseId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetHouseDetailsResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/GetHouseDetailsResponse'
        '400':
          description: House with given id not found
  '/houses/{houseId}/members':
    get:
      tags:
        - Houses
      summary: Get list of members of a house
      description: ''
      operationId: listAllMembersOfHouse
      parameters:
        - in: path
          name: houseId
          required: true
          schema:
            type: string
        - in: query
          name: pageable
          required: false
          schema:
            $ref: '#/components/schemas/Pageable'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListHouseMembersResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ListHouseMembersResponse'
    post:
      tags:
        - Houses
      summary: Add members of a house
      description: ''
      operationId: addHouseMembers
      parameters:
        - in: path
          name: houseId
          required: true
          schema:
            type: string
      requestBody:
        description: Add members request body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddHouseMemberRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/AddHouseMemberRequest'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddHouseMemberResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/AddHouseMemberResponse'
        '404':
          description: House with given Id not found
  '/houses/{houseId}/members/{memberId}':
    delete:
      tags:
        - Houses
      summary: Delete member from a house
      description: ''
      operationId: deleteHouseMember
      parameters:
        - in: path
          name: houseId
          required: true
          schema:
            type: string
        - in: path
          name: memberId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: successful operation
        '404':
          description: Member with given Id not found
components:
  schemas:
    CreateUserRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 8
          maxLength: 80
    CreateUserResponse:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
        email:
          type: string
    GetUserDetailsResponse:
      type: object
      required:
        - users
      properties:
        users:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/GetUserDetailsResponseUser'
    GetUserDetailsResponseUser:
      type: object
      properties:
        userId:
          type: string
        name:
          type: string
        email:
          type: string
        communityIds:
          type: array
          uniqueItems: true
          items:
            type: string
    Pageable:
      description: Pageable query parameters
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
    GetHouseDetailsResponse:
      description: List of houses response
      type: object
      properties:
        houses:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/CommunityHouse'
    CommunityHouse:
      description: Community house
      type: object
      properties:
        houseId:
          type: string
          example: '123'
        name:
          type: string
          example: 'MyHome Community House'
    ListHouseMembersResponse:
      description: List of house members response
      type: object
      properties:
        members:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/HouseMember'
    HouseMember:
      description: Community house member
      type: object
      properties:
        memberId:
          type: string
          example: '123'
        name:
          type: string
          example: 'John Doe'
    AddHouseMemberRequest:
      description: Add House Member Request
      type: object
      properties:
        members:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/HouseMemberRequest'
    HouseMemberRequest:
      description: House Member Request
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 123
        memberId:
          type: string
          example: '123'
        name:
          type: string
          example: 'John Doe'

    AddHouseMemberResponse:
      description: List of house members response
      type: object
      properties:
        members:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/HouseMember'
